version: '3.8'

services:

  guicpay-api:
    image: guilhermeasilva/guicpay:latest
    networks:
      - nginx_network
    environment:
      - APP_PORT=3000
      - TRANSACTION_TIMEOUT=15s
      - NOTIFICATION_SERVICE_URL=https://run.mocky.io/v3/5794d450-d2e2-4412-8131-73d0293ac1cc
      - AUTHORIZE_SERVICE_URL=https://run.mocky.io/v3/54dc2cf1-3add-45b5-b5a9-6bf7e7f1f4a6
      - REDIS_ADDRESS=redis:6379
      - DATABASE_URL=postgres://user:ozApGB6je7ZbK8wRGOh2zHG0qDfGcTi1yO78ieiQMN7eim2NfW@postgres:5432/db?sslmode=disable
      - JWT_SECRET=SECRET
      - TRACE_COLLECTOR_URL=http://zipkin:9411/api/v2/spans
      - USE_MOCK_SERVER=true
    networks:
      - nginx_network
      - app_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
      resources:
        limits:
          cpus: '0.25'
          memory: 128M

  redis:
    image: redis:latest
    networks:
      - app_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]

  zipkin:
    image: openzipkin/zipkin:latest
    networks:
      - app_network
    volumes:
      - zipkin_data:/zipkin
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  zipkin_data:

networks:
  nginx_network:
    external: true
  app_network:
    external: true