version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    secrets:
      - ssl_cert
      - ssl_cert_key
    networks:
      - nginx_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
secrets:
  ssl_cert:
    external: true
  ssl_cert_key:
    external: true

networks:
  nginx_network:
    external: true